### ISSUE TITLE
Toml internal validation

### ISSUE THREAD

**Issue by mattloose** [LooseLab/ru#1]
When a TOML file is loaded, it should be validated to ensure no errors in reference names etc.

**Comment by alexomics** [comment]
Wider parameter validations:
 - Load TOML before analysis function -> create function in `utils.py`
 - load text file into list. Eg if `targets` is str read into list, otherwise parse array
 - Test for validity against schema -> move to static data
    - update validator to use internal static file
 - Open mapper/Aligner to pass to analysis function
 - Potentially, restructure analysis function to consume different arguments
    ```python
    def analysis_function(
        client,
        batch_size=512,
        throttle=0.1,
        unblock_duration=0.5,
        chunk_logger=None,  # Change to logger
        paf_logger=None,    # Change to logger
        toml_path=None,
        flowcell_size=512,
        dry_run=False,
        mapper=None,        # mappy
    )
    ```

**Comment by alexomics** [comment]
Wider parameter validations:
 - Load TOML before analysis function -> create function in `utils.py`
 - load text file into list. Eg if `targets` is str read into list, otherwise parse array
 - Test for validity against schema -> move to static data
    - update validator to use internal static file
 - Open mapper/Aligner to pass to analysis function
 - Potentially, restructure analysis function to consume different arguments
    ```python
    def analysis_function(
        client,
        batch_size=512,
        throttle=0.1,
        unblock_duration=0.5,
        chunk_logger=None,  # Change to logger
        paf_logger=None,    # Change to logger
        toml_path=None,
        flowcell_size=512,
        dry_run=False,
        mapper=None,        # mappy
    )
    ```

**Comment by alexomics** [comment]
bf105b6 should complete these changes
