### ISSUE TITLE
CPU basecalling - increased number of reads processed together?

### ISSUE THREAD

**Issue by AlexanderDilthey** [LooseLab/ru#27]
First of all, installing the new Read Until code works like a charm! Thanks a lot!

We're trying to get Read Until going with CPU basecalling. We're using a machine with 40 physical Xeon Silver cores, and live basecalling in MinKnow (fast mode) seems to easily keep up with the incoming data from from the bulk FAST5 test file, so I hope that this should, at least in principle, not be a hopeless undertaking.

`ru_generators` starts up fine, but there may be some kind of communications issue between the Read Until code and the Guppy basecalling server. Specifically, this is the output I get from `ru_generators`:

~~~~
2020-02-29 18:24:00,807 ru.ru_gen 1R/0.33953s
2020-02-29 18:24:47,350 ru.ru_gen 148R/46.54283s
2020-02-29 18:28:25,598 ru.ru_gen 205R/218.24645s
~~~~
(and then nothing more, so maybe things are slowing down over time)

I assume that 'R' specifies the number of reads, and the number after that specifies the average amount of time spent on the initial basecalling per read? ... so it seems that the number of reads lumped together is much higher than in the example provided?

Guppy server command: 

`./guppy_basecall_server --config dna_r9.4.1_450bps_hac.cfg --port 5550 --log_path guppy_log.txt --ipc_threads 3 --max_queued_reads 2000 --data_path ../data --num_callers 1 --cpu_threads_per_caller 18` 

Read Until command: 

`./ru_generators --device MN25472 --experiment-name "test2" --toml example.toml --log-file read_until_log.txt`

Apart from that, everything is exactly identical to the default / example files.

**Comment by mattloose** [comment]
A few things you can try here. The first two can be tested on playback. The third may help on playback..

1. In the example toml file are you using the hac or fast basecalling model. I suspect the high accuracy model. 
Try changing:
https://github.com/LooseLab/ru/blob/c1ae77d157f608fcc65d2a3fa3750cd72b84ee83/example.toml#L2
to:
config_name = "dna_r9.4.1_450bps_fast"
This will tell Guppy to basecall using the fast model - so more efficient by slightly lower accuracy (likely doesn't matter for your purposes). 

2. Because you are falling behind, you will be grabbing larger and larger chunks of data to basecall and so fall further behind. Try setting the line https://github.com/LooseLab/ru/blob/c1ae77d157f608fcc65d2a3fa3750cd72b84ee83/example.toml#L13:
max_chunks = inf
to
max_chunks = 4
Note you need to do this in each condition. 
This will have the effect of unblocking any read that cannot be mapped after around 1.6 seconds. In our testing this hasn't seemed to have a significant negative impact. But there will be some correct reads that you end up unblocking.

3. If you see large numbers of reads building up like this try pausing the run and then restarting it. This normally clears any back log and gets you back to asynchronous processing of the reads. 

Troubleshooting all this on a playback run before trying on a real flowcell is definitely the way to go!

**Comment by AlexanderDilthey** [comment]
Marvelous, thank you! Will try out and report back!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattloose** [comment]
Also - just to check that you have set the value of break_reads_after_seconds to 0.4 in the sequencing***.toml file?

**Comment by AlexanderDilthey** [comment]
Hi Matt,

1. I've changed `break_reads_after_seconds` to 0.4 (from 1.0 previously), but this change in isolation doesn't seem to do much - is 0.4 or 1.0 appropriate for CPU basecalling?

2. Changing to the fast model significantly increases speed (at still increased 'R' vaues).

3. Setting `max_chunks = 4` leads to decreased values reported for `R` and also to a decrease in the reported times (around 0.1s).

This seems all very positive, right? I am still trying to figure out whether there's an interaction between `break_reads_after_seconds` and the other parameters, but meanwhile some hardware issues have cropped up up.... I'll keep you updated.

By the way, CPU usage of the Guppy basecalling server when using the value 0.4 for `break_reads_after_seconds`, the fast model, and `max_chunks = 4` sits comfortably at around 3000% (on a 40 core machine), which seems to suggest that there's still some slack...

**Comment by mattloose** [comment]
This all sounds good. 0.4 seconds is better than 1 as you will unblock correctly identified material sooner - and you definitely want to do that. You probably have a lot of headroom in the system. Have you tried running with the hac basecaller using 0.4 seconds and a mac chunk of 4? It may work. As long as your average time doesn’t climb above 0.4 you should be fine.

**Comment by mattloose** [comment]
@alexomics could you review this and see if we need to add any changes to docs - otherwise close if @AlexanderDilthey is happy.

**Comment by AlexanderDilthey** [comment]
Very happy - have not tried to revert to `break_reads_after_seconds = 0.4` - now experimenting with MHC enrichment... ;-)

Thank you!

**Comment by mattloose** [comment]
Cool - we’ve seen between 30-45x coverage on mhc with a simple targeting strategy. We’ve been running those alongside our cancer panels a bit. Good luck!
