### ISSUE TITLE
Read-until for short amplicons

### ISSUE THREAD

**Issue by AlexanderDilthey** [LooseLab/ru#31]
Hi Matt,

We're using the amazing ARTIC protocol for Covid-19 sequencing but observe that there is sometimes significant individual-amplicon dropout. The amplicons are relatively short (~400). Would it be possible to modify your code so that reject decisions are made after the first, say, 20 or 40 bases, with the idea of enriching under-represented amplicons?

Cheers,

Alex

**Comment by mattloose** [comment]
Hi Alex,

The ARTIC protocol is indeed brilliant. However, there have been some issues with two of the primer sites and this is discussed on line. It would be worth contacting ARTIC about this directly - there is also a preprint describing a potential fix.

With respect to running read until on these short amplicons we are currently limited to grabbing a very specific smallest amount of data due to the way MinKNOW itself functions. We are trying to get resources to look at this in a bit more detail but I suspect the primer issue I allude to above may be what you are seeing and fixing this would resolve your problem better than read until would.

Best

Matt

**Comment by AlexanderDilthey** [comment]
Hi Matt,

Yes, I saw the discussion about the primer issues - copying in the link to the preprint in case someone else stumbles over this entry: https://www.biorxiv.org/content/10.1101/2020.03.10.985150v1?rss=1

To confirm, what we observe is consistent with the described primer issues - we're currently sequencing one library where the problem occurs, and the thought crossed my mind that RU could be used on the ongoing run as an immediate fix ;-).

I am closing this now, thank you for responding so quickly!

Cheers,

Alex
